[package]
name = "rocket-crud"
version = "0.1.0"
edition = "2021"

[dependencies]
mongodb = "2.8.2"
rocket = "0.5.1"
rocket_contrib = "0.4.11"
serde = { version = "1.0.203", features = ["derive"] }
serde_json = "1.0.117"
tokio = { version = "1.37.0", features = ["full"] }
